### ISSUE TITLE
Fix example_scens.py

### ISSUE THREAD

**Issue by pausz** [fpsim/fpsim#284]
```
Final population size: 215.
Run finished for "senegal--1" after 1.3 s
Traceback (most recent call last):
  File "/home/paula/Projects/IDM/dev-fpsim/fpsim/examples/example_scens.py", line 80, in <module>
    meth_fig = scens.plot('method', colors=[color for color in colors.values()])
  File "/home/paula/Projects/IDM/dev-fpsim/fpsim/fpsim/scenarios.py", line 426, in plot
    return self.msim.plot(to_plot=to_plot, plot_sims=plot_sims, **kwargs)
  File "/home/paula/Projects/IDM/dev-fpsim/fpsim/fpsim/sim.py", line 1304, in plot
    ax.stackplot(total_df["Year"].unique(), percentage_by_method, labels=method_names, colors=colors)
  File "/home/paula/miniconda3/envs/py310-fpsim-dev/lib/python3.10/site-packages/matplotlib/__init__.py", line 1446, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/paula/miniconda3/envs/py310-fpsim-dev/lib/python3.10/site-packages/matplotlib/stackplot.py", line 115, in stackplot
    coll = axes.fill_between(x, first_line, stack[0, :],
  File "/home/paula/miniconda3/envs/py310-fpsim-dev/lib/python3.10/site-packages/matplotlib/__init__.py", line 1446, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/paula/miniconda3/envs/py310-fpsim-dev/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 5425, in fill_between
    return self._fill_between_x_or_y(
  File "/home/paula/miniconda3/envs/py310-fpsim-dev/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 5346, in _fill_between_x_or_y
    where = where & ~functools.reduce(
ValueError: operands could not be broadcast together with shapes (31,) (93,) 

```

**Comment by pausz** [comment]
Looks like it's a concatentation problem
In sim.plot():
  -> if to_plot==method:
       ->  percentage_by_method is a list with 10 elements, and each element is a list of len 31 (on `main`) but on the development branch each element has len 93.

**Comment by pausz** [comment]
Sim names are broken:
On main:
```[Sim("Baseline"; n=100; 2010-2040; results: b=192 ☠=27 pop=257), Sim("intro new method, double init"; n=100; 2010-2040; results: b=195 ☠=26 pop=261), Sim("intro new method, 20% switching"; n=100; 2010-2040; results: b=198 ☠=22 pop=265)]```

On dev branch:
```[Sim("senegal--1"; n=100; 2010-2040; results: b=159 ☠=36 pop=219), Sim("senegal--1"; n=100; 2010-2040; results: b=159 ☠=28 pop=227), Sim("senegal--1"; n=100; 2010-2040; results: b=150 ☠=31 pop=215)]```

**Comment by pausz** [comment]
Scenarios.make_sims relies on sim.label == None (default value on main), to apply the scenario label to sim.label, but on the dev branch sim.label is never None.  This results in multisim aggregating results of 3 different simulations, because they all have the same label.
