### ISSUE TITLE
track_mcpr() element-wise comparison is comparing ints to strings 

### ISSUE THREAD

**Issue by robynstuart** [fpsim/fpsim#302]
From running `benchmark_empowerment.py`:

```
/Users/robynstuart/anaconda3/envs/starsim/lib/python3.9/site-packages/numpy/lib/arraysetops.py:733: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/Users/robynstuart/Documents/git/fpsim/fpsim/sim.py:391: RuntimeWarning: invalid value encountered in scalar divide
  self.results['mcpr'][ti] = r.on_methods_mcpr / (r.no_methods_mcpr + r.on_methods_mcpr)
/Users/robynstuart/Documents/git/fpsim/fpsim/sim.py:393: RuntimeWarning: invalid value encountered in scalar divide
  self.results['acpr'][ti] = r.on_methods_acpr / (r.no_methods_acpr + r.on_methods_acpr)
```

The last two must be because the result arrays aren't populated, but the first is mysterious to me - where is it coming from? This also occurs when running `test_simple()` within `test_sim.py`.

**Comment by pausz** [comment]
Traceback
```
Traceback (most recent call last):
  File "/home/paula/Projects/IDM/dev-fpsim/fpsim/examples/example_sim.py", line 23, in <module>
    sim.run()
  File "/home/paula/Projects/IDM/dev-fpsim/fpsim/fpsim/sim.py", line 343, in run
    self.step()
  File "/home/paula/Projects/IDM/dev-fpsim/fpsim/fpsim/sim.py", line 296, in step
    step_results = self.people.update()
  File "/home/paula/Projects/IDM/dev-fpsim/fpsim/fpsim/people.py", line 924, in update
    self.track_mcpr()
  File "/home/paula/Projects/IDM/dev-fpsim/fpsim/fpsim/people.py", line 753, in track_mcpr
    numerator = np.isin(self.method, modern_methods)
  File "<__array_function__ internals>", line 200, in isin
  File "/home/paula/miniconda3/envs/py310-fpsim-dev/lib/python3.10/site-packages/numpy/lib/arraysetops.py", line 890, in isin
    return in1d(element, test_elements, assume_unique=assume_unique,
  File "<__array_function__ internals>", line 200, in in1d
  File "/home/paula/miniconda3/envs/py310-fpsim-dev/lib/python3.10/site-packages/numpy/lib/arraysetops.py", line 733, in in1d
    mask |= (ar1 == a)
FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
```

**Comment by pausz** [comment]
Maybe I'm missing something about the overall logic surrounding this line 
```
    numerator = np.isin(self.method, modern_methods)
```
but self.method is an array of integers (dtype int64), and `modern_methods` is a list ['pill', 'iud', 'inj', 'cond', 'btl', 'impl', 'othmod'], so numerator is always a boolean array with False.
